### ISSUE TITLE
MVPリリースレビュー依頼

### ISSUE THREAD

**Issue by Micknomick** [Micknomick/DMission#70]
## 各種情報
サービスの概要とMVPで検証する事柄：
-サービス概要
「DMission」は1つの目的(mission)を果たすためにチーム員でタスクを作成し、 誰がそのタスクをいつまでにやらなければいけないかを明確にできるTODOアプリケーションです。
-検証する事柄
・ユーザー認証
・mission,taskのcrud機能

サービス名：
Dmission

サービスURL：
https://dmission-a0c003887d75.herokuapp.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] ユーザー登録機能
- [x] 通常ログイン機能
- [x] ログアウト機能
- [x] タスク追加機能
- [x] ミッション追加機能
- [x] お問い合わせ、利用規約、プライバシーポリシー

READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください。

## READMEレビュー時から変更した機能
開発途中でMVPリリース時点で作らなくなった機能や追加した機能があれば記載してください。なければこの項目は省略してください。

- [ ] ユーザー登録機能
- [ ] パスワードリセット機能

## サービスイメージがわかるようなスクリーンショット等
特に管理画面など通常ユーザーが触れない機能があったら共有してください。

**Comment by ippei-shimizu** [comment]
下記機能について確認ができませんでした。
ご確認の上、必要であれば修正等を行ってください。
もし実装できているのであれば、コメントに確認手順を詳しく記載してください。
上記いずれかのご対応の上、RUNTEQアプリから再提出してください。

--- 

- 未ログイン状態で、https://dmission-a0c003887d75.herokuapp.com/tasks にアクセスしたところ以下のエラーが発生しました。未ログイン状態でアクセスできないページであれば、リダイレクト処理を入れるか、そもそもメニューに表示させないようにしてください。

[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/fc1671b6c99c7aa030b673fd797cdce3.png)](https://startup-technology.gyazo.com/fc1671b6c99c7aa030b673fd797cdce3)

**Comment by Micknomick** [comment]
お世話になります。
お忙しい中、ご確認いただきありがとうございます。
tasks_controllerにbefore_action :authenticate_user!を追記し、
ログインしていないとアクセスできないようにいたしました。
よろしくお願いいたします。
